server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 78c9769d-aba0-486b-8876-862032f00cb7
      config:
        server-addr: localhost:8848
        namespace: 78c9769d-aba0-486b-8876-862032f00cb7
        file-extension: yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql_lin?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ecommerce.user.domain